### ISSUE TITLE
Generate image from cochleogram

### ISSUE THREAD

**Issue by dgutierrezATC** [jpdominguez/NAVIS-Tool#1]
It would be nice to have a button which generates an image from the cochleogram representation when a .aedat file is loaded.

**Comment by jpdominguez** [comment]
This has already been added in the File menu with the option Save Cochleogram and it will be available in the next update.

**Comment by jpdominguez** [comment]
This has already been added in the File menu with the option Save Cochleogram and it will be available in the next update.
